[package]
name = "andarilho"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0"
thirtyfour = "0.31.0"
regex = "1.5"
serde = "1"
serde_json = "1"
urlencoding = "1"
tokio = "1.36.0"
