version: '3'
services:
  andarilho:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: 'host'
    environment:
      - ROCKET_PORT=80
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-firefox:latest
    shm_size: 2gb
    ports:
      - 4444:4444
